### ISSUE TITLE
Reading an item doesn't return the 'username' field

### ISSUE THREAD

**Issue by jli-cparta** [1Password/vault-plugin-secrets-onepassword#15]
For some reason, the 'username' field isn't retrieved. We get the 'Full name' and 'password' fields, but not username?

That can't be right. There's an empty field at the start of the 'data' section - might be that it's supposed to go there?

```
$ vault read -format=json op/vaults/servers/items/server1
{
  "request_id": "1fc2d13d-c9a6-b9cf-dd21-a2964ebfd423",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "": "",
    "Full name": "John Smith",
    "password": "..."
  },
  "warnings": null
}
```

**Comment by jli-cparta** [comment]
Looking at the entry using another client, it looks and works fine.
Copying the item yields another non-functioning item using the Vault plugin.
However, if I create an entirely new item using the app or web UI, it *does* send the username correctly.

**Comment by jpcoenen** [comment]
Hi @jli-cparta,

Thank you for reaching out.

> Looking at the entry using another client, it looks and works fine.
> Copying the item yields another non-functioning item using the Vault plugin.
> However, if I create an entirely new item using the app or web UI, it does send the username correctly.

This is some really helpful information. Could you maybe share the response of a direct call to Connect with `curl`? So for example:

```bash
export OP_CONNECT_TOKEN=<token>
export OP_CONNECT_HOST=http://localhost:8080
export VAULT_UUID=fuacthv5i7gextkqv45g7algw4
export ITEM_UUID=47dp6f47xabgwwoa7w4vscfenq
curl -H "Authorization: Bearer $OP_CONNECT_TOKEN" "$OP_CONNECT_HOST/v1/vaults/$VAULT_UUID/items/$ITEM_UUID" | jq
```

The part I am mostly interested in, is the entry in the `fields` list for the `username`. The other parts you can leave out. So, for example:

```json
    {
      "id": "username",
      "type": "STRING",
      "purpose": "USERNAME",
      "label": "username",
      "value": "my-username"
    },
```

I am hoping that will provide some extra information as to why the field is ignored by the plugin.

**Comment by jli-cparta** [comment]
I'll try to get that for you. The initial entries that were problematic have been lost, but I might have others in the database. I'll see if I can find one.

**Comment by jli-cparta** [comment]
@jpcoenen Found one. This one is doubly broken -- neither username nor password is returned.

```
$ vault read op/vaults/zqj5owhainjrnffjupqrchhhue/items/32bs4tz3yijasze6tjcahqkada
Key                                            Value
---                                            -----
n/a                                            n/a
URL                                            default
notesPlain                                     n/a
subscription-register-account-method           1
subscription-register-activation-key-method    0
```

```json
{
  "id": "32bs4tz3yijasze6tjcahqkada",
  "title": "REDACTED",
  "urls": [
    {
      "primary": true,
      "href": "https://192.168.1.2"
    }
  ],
  "version": 1,
  "vault": {
    "id": "zqj5owhainjrnffjupqrchhhue"
  },
  "category": "LOGIN",
  "sections": [
    {
      "id": "Section_e2izaqbqbrenpmzbk6h6fk4yem",
      "label": "Saved on 192.168.1.2"
    }
  ],
  "fields": [
    {
      "id": "username",
      "type": "STRING",
      "purpose": "USERNAME",
      "value": "REDACTED"
    },
    {
      "id": "password",
      "type": "CONCEALED",
      "purpose": "PASSWORD",
      "value": "REDACTED"
    },
    {
      "id": "",
      "type": "STRING"
    },
    {
      "id": "",
      "type": "STRING",
      "label": "subscription-register-account-method",
      "value": "1"
    },
    {
      "id": "",
      "type": "STRING",
      "label": "subscription-register-activation-key-method",
      "value": "0"
    },
    {
      "id": "",
      "type": "STRING",
      "value": "✓"
    },
    {
      "id": "",
      "type": "STRING"
    },
    {
      "id": "notesPlain",
      "type": "STRING",
      "purpose": "NOTES",
      "label": "notesPlain"
    },
    {
      "id": "quryyh7g4b5hr3gdvyt3kedxxy",
      "section": {
        "id": "Section_e2izaqbqbrenpmzbk6h6fk4yem"
      },
      "type": "STRING",
      "label": "URL",
      "value": "default"
    }
  ],
  "lastEditedBy": "R7KO7KMQ2VH6TMYXTR5GHMB76Y",
  "createdAt": "2021-08-09T15:12:32Z",
  "updatedAt": "2021-08-09T15:12:32Z"
}
```

**Comment by edif2008** [comment]
Hey @jli-cparta!
Can you provide some details about the command you run to create the item provided [here](https://github.com/1Password/vault-plugin-secrets-onepassword/issues/15#issuecomment-939862304) for replicating the issue that you're facing? That can help us identify faster what goes wrong with getting items with Connect.

**Comment by jpcoenen** [comment]
After some digging, we think we have reproduced the issue. The latest release of Connect (`1.5.0`) contains a fix for what we found.  

I am going to close the issue for now. If the issue can still be reproduced with `1.5.0`, feel free to re-open the issue.
