### ISSUE TITLE
Cannot configure plugin

### ISSUE THREAD

**Issue by akamensky** [1Password/vault-plugin-secrets-onepassword#18]
```
# ./bin/vault write op-connect/config @conf/op-connect-config.json 
Error writing data to op-connect/config: Error making API request.

URL: PUT http://localhost:8200/v1/op-connect/config
Code: 404. Errors:

* no handler for route 'op-connect/config'
```

**Comment by akamensky** [comment]
FWIW, the Vault version is 1.8.1, but it looks like plugin is using SDK version 1.1.2, which is quite different and has breaking API changes.

**Comment by akamensky** [comment]
Another error pointing to outdated API:

```
# ./bin/vault secrets disable op/
Error disabling secrets engine at op/: Error making API request.

URL: DELETE http://localhost:8200/v1/sys/mounts/op
Code: 400. Errors:

* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by SachinMaharana** [comment]
I am having the same issue. Were you able to find any solution for this?

**Comment by akamensky** [comment]
We removed Vault from the equation and using 1Password gateway instead. @SachinMaharana

**Comment by jillianwilson** [comment]
Hi all, thank you for raising this issue. We will look into the issue, and update here when resolved.

**Comment by injectedfusion** [comment]
> Hi all, thank you for raising this issue. We will look into the issue and update here when resolved.

I reproduced this same bug after running through the tutorial posted at https://medium.com/hashicorp-engineering/1password-secrets-automation-with-hashicorp-vault-a1995c040. I am still hoping for an update soon. Many Thanks!

**Comment by wxt9861** [comment]
Ran into this issue as well using the tutorial. I was able to solve it by writing config to op/ instead of op-connect/ like below.

```vault write op/config @conf/op-connect-config.json ```

**Comment by ahussey-redhat** [comment]
The correct name seems to be `op` rather than `op-connect`
EG
```bash
./bin/vault write op/config @conf/op-connect-config.json 
```

Discovered this based off of the `path` when reviewing `vault secrets list`
